require("prototypes.categories.ammo-category")
require("prototypes.entity.turrets")
require("prototypes.item.ammo")
require("prototypes.item.gun")
require("prototypes.recipe.ammo")
require("prototypes.technology.military-upgrades")
require("prototypes.technology.technology")
